# Линейная алгебра

## Вектор

v = $\begin{bmatrix} v_1 \\ v_2 \\ . \\ . \\ v_n \end{bmatrix}$

#### Линейная комбинация векторов

Комбинация векторного сложения и скалярного умножения векторов

с*$\begin{bmatrix} v_1 \\ v_2\\ .\\ . \\ v_n \end{bmatrix}$ + d*$\begin{bmatrix} w_1 \\ w_2 \\ .\\ . \\ w_n \end{bmatrix}$ = $\begin{bmatrix} c * v_1 + d * w_1 \\ c * v_2 + d * w_2 \\ .\\ . \\ c * v_n + d * w_n\end{bmatrix}$

#### Длина вектора
$v = \begin{bmatrix} v_1 \\ v_2\\ .\\ . \\ v_n \end{bmatrix}$

$|v| = \sqrt{v_1^2 + v_2^2 + ... + v_n^2}$


#### Скалярное произведение векторов

$\begin{bmatrix} v_1 \\ v_2\\ .\\ . \\ v_n \end{bmatrix}$ . $\begin{bmatrix} w_1 \\ w_2\\ .\\ . \\ w_n \end{bmatrix}$ = 
$v_1 * w_1 + v_2 * w_2 + \dots + v_n * w_n $

![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Dot_product_cosine_rule.svg/106px-Dot_product_cosine_rule.svg.png)

По теореме косинусов: 

$|a|^2 + |b|^2 - 2*|a||b|\cos{\theta} = |a - b|^2$.

$|a-b|^2 = (a-b).(a-b) = a.a - 2*a.b + b.b = |a|^2 - 2*a.b + |b|^2$.

$|a|^2 - 2*a.b + |b|^2 = |a|^2 + |b|^2 - 2*|a||b|\cos{\theta}$.

Сокращаем:

$\boldsymbol{a.b = |a||b|\cos{\theta}}$.

#### Проекция векторов

![Image](https://upload.wikimedia.org/wikipedia/commons/9/98/Projection_and_rejection.png)

$|a_1| = |a|\cos{\theta}$.

$a.b = |a||b|\cos{\theta} \Rightarrow \boldsymbol{|a_1| = \frac{a.b}{|b|}}$.

$a_1 = \frac{b}{|b|}|a_1| \Rightarrow \boldsymbol{a_1 = b\frac{a.b}{|b|^2}}$.

#### Замена базиса
Применимо только если вектора в новом базисе ортогональны. Для замены базиса необходимо определить длину проекций вектора на новые базисные в единицах их длины.

$v = \begin{bmatrix} v_1 \\ . \\ .\\ v_n \end{bmatrix}, u_1 = \begin{bmatrix} u_{11} \\ . \\ .\\ v_{1n} \end{bmatrix} \dots u_n = \begin{bmatrix} u_{n1} \\ . \\ .\\ v_{nn} \end{bmatrix}$

$v^u = \begin{bmatrix} |v_1^{u_1}| \\ . \\ .\\ |v_n^{u_n}| \end{bmatrix}$, где:

$|v_i^{u_i}| = \frac{a.u_i}{|u_i|^2}$

## Матрица

$c = \begin{bmatrix} 
    c_{1,1} & c_{1,2} & ... & c_{1,m} \\
    c_{2,1} & c_{2,2} & ... & c_{2,m} \\
    ... \\
    c_{n,1} & c_{n,2} & ... & c_{n,m} 
\end{bmatrix}$

#### Умножение матриц

$c_{i,j} = a \times b = \sum_{k=1}^{m} a_{i,k}*b_{k,j} $

#### Матричные трансформации

Умножение матрицы на вектор можно рассматривать, как трансформацию базисных векторов.

$c = \begin{bmatrix} 
    c_{1,1} & c_{1,2} \\
    c_{2,1} & c_{2,2}\\
\end{bmatrix}, 
\bar{e_1} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}, 
\bar{e_2} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$

$c \times \bar{e_1} = \begin{bmatrix} c_{1,1} \\ c_{2,1} \end{bmatrix}$ 

$c \times \bar{e_2} = \begin{bmatrix} c_{1,2} \\ c_{2,2} \end{bmatrix}$

##### Единичная матрица

$I = \begin{bmatrix} 
    1 & 0 \\
    0 & 1\\
\end{bmatrix}$ - не меняет вектор.

$I \times \bar{e_1} = \bar{e_1}$

$I \times \bar{e_2} = \bar{e_2}$

##### Масштабирование

$c = \begin{bmatrix} 
    m_1 & 0 \\
    0 & m_2\\
\end{bmatrix}$ - масштибирует вектор вдоль соответствующих осей.

In [75]:
import numpy as np

c = np.matrix(
    [[3, 0],
     [0, 4]])
v = np.array(
    [2,
     3])

print(np.dot(c,v))

[[ 6 12]]


##### Симметричное отображение

$c = \begin{bmatrix} 
    -1 & 0 \\
    0 & -1\\
\end{bmatrix}$ - симметрично отображает вдоль соответствующих осей.

In [81]:
c = np.matrix(
    [[-1, 0],
     [0, -1]])
v = np.array([2,3])

print(np.dot(c,v))

[[-2 -3]]


##### Перемена базисных векторов

$c = \begin{bmatrix} 
    0 & 1 \\
    1 & 0 \\
\end{bmatrix}$ - меняет между собой базисные вектора.

In [80]:
c = np.matrix(
    [[0, 1],
     [1, 0]])
v = np.array([2,3])

print(np.dot(c,v))

[[3 2]]


##### Наклон вдоль осей

$c = \begin{bmatrix} 
    1 & 1 \\
    0 & 1 \\
\end{bmatrix}$.

![title](images/lin_al_mtx_trnsfrm.png)

In [132]:
c = np.matrix(
    [[1, 1],
     [0, 1]])
v = np.array([0.5,1])

print(np.dot(c,v))

[[1.5 1. ]]


##### Вращение

$c = \begin{bmatrix} 
    \cos{\theta} & \sin{\theta} \\
    -\sin{\theta} & \cos{\theta} \\
\end{bmatrix}$.